# In Floodgate bedrock player data is send encrypted
# The following value should point to the key Floodgate generated.
# The public key should be used for the Geyser(s) and the private key for the Floodgate(s)
key-file-name: key.pem

disconnect:
  # The disconnect message Geyser users should get when connecting
  # to the server with an invalid key
  invalid-key: Please connect through the official Geyser
  # The disconnect message Geyser users should get when connecting
  # to the server with the correct key but not with the correct data format
  invalid-arguments-length: Expected {0} arguments, got {1}. Is Geyser up-to-date?
