# In Floodgate bedrock player data is send encrypted
# The following value should point to the key Floodgate generated.
# The public key should be used for the Geyser(s) and the private key for the Floodgate(s)
key-file-name: key.pem

# Floodgate prepends a prefix to bedrock usernames to avoid conflicts
# However, certain conflicts can cause issues with some plugins so this prefix is configurable using the property below
# It is recommended to use a prefix that does not contain alphanumerical to avoid the possibility of duplicate usernames.
username-prefix: "*"

# Should spaces be replaced with '_' in bedrock usernames?
replace-spaces: true

# Should Bungeecord send the bedrock player data to the servers it is connecting to?
# This requires Floodgate to be installed on the servers.
# You'll get kicked if you don't use the plugin. The default value is false because of it
send-floodgate-data: false

disconnect:
  # The disconnect message Geyser users should get when connecting
  # to the server with an invalid key
  invalid-key: Please connect through the official Geyser
  # The disconnect message Geyser users should get when connecting
  # to the server with the correct key but not with the correct data format
  invalid-arguments-length: Expected {0} arguments, got {1}. Is Geyser up-to-date?

# Configuration for player linking
player-link:
  # Whether to enable the linking system. Turning this off will prevent
  # players from using the linking feature even if they are already linked.
  enable: false
  # The type of storage system you want to use
  # Currently implemented: SQLite
  type: sqlite
  # Whether to allow the use of /linkaccount and /unlinkaccount
  # You can also use allow specific people to use the commands using the
  # permissions floodgate.linkaccount and floodgate.unlinkaccount.
  # This is only for linking, already connected people will stay connected
  allow-linking: true
  # The amount of time until a link code expires in seconds
  link-code-timeout: 300
  
